
development:
  adapter: postgresql
  encoding: unicode
  database: emberchat_development
  pool: 5
  username: vagrant
  password:

test:
  adapter: postgresql
  prepared_statements: false

production:
  adapter: postgresql
  statement_limit: 200
